language: java
jdk:
  - 'oraclejdk8'
  
addons:
  apt:
    packages:
      - oracle-java8-set-default
  
install:
  - './gradlew clean build -x test'
    
script:
  - './gradlew :black-duck-broker:test'
  - './gradlew :black-duck-perceiver:test'
  - './gradlew :black-duck-img-facade:test'

after_success:
  - './gradlew :{black-duck-broker,black-duck-perceiver,black-duck-img-facade}:{test,jacocoTestReport,coveralls}'
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
