language: python
python:
  - '2.7'
jdk:
  - 'oraclejdk8'
  
addons:
  apt:
    packages:
      - oracle-java8-set-default
  
install:
  - './gradlew clean build -x test'
    
script:
  - './gradlew :black-duck-broker:test'

after_success:
  - './gradlew :black-duck-broker:test :black-duck-broker:jacocoTestReport :black-duck-broker:coveralls'
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
