language: python
python:
  - '2.7'
jdk:
  - 'oraclejdk8'
  
addons:
  apt:
    packages:
      - oracle-java8-set-default
  
install:
  - './gradlew clean build -x test'
  
before_script:
  - 'pip install proboscis'
  
script:
  - './gradlew :black-duck-broker:test'
  - 'cd black-duck-decorator/test && python run_tests.py && cd ../..'

after_success:
  - './gradlew :black-duck-broker:test :black-duck-broker:jacocoTestReport :black-duck-broker:coveralls'
  - 'curl https://copilot.blackducksoftware.com/scripts/init/gradle -o bds_init.gradle'
  - './gradlew --init-script bds_init.gradle buildBom -DbdsPluginVersion=5.0.2'
  - 'bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)'
