server:
  port: 8891
spring:
  main:
    banner-mode: 'OFF'
  application:
    name: black-duck-perceiver
application:
  realm: BlackDuckSoftware
  event-monitor-service:
    polling-period-seconds: 5
  dumper-service:
    polling-period-seconds: 1800
  scan-results-service:
    polling-period-seconds: 1200
cf:
  baseUrl: https://api.bosh-lite.com
  skip-ssl-validation: false
  oauth2:
    client:
      id: Cloud Foundry
      grantType: client_credentials
      clientId: black-duck-broker
      clientSecret: 'cf_pass'
      accessTokenUri: https://uaa.bosh-lite.com/oauth/token
      scope: cloud_controller.admin
perceptor:
  baseUrl: http://localhost # http://host.docker.internal
  port: 3001
broker:
  baseUrl: http://localhost # http://host.docker.internal
  port: 8890
  basicAuth:
    user: cf_user
    pass: cf_pass
logging:
  level:
    root: WARN
    com:
      blackducksoftware:
        integration: DEBUG