server:
  port: ${SERVER_PORT:8891}
spring:
  main:
    banner-mode: 'OFF'
  application:
    name: black-duck-perceiver
application:
  realm: ${APPLICATION_REALM}
  eventMonitorService:
    pollingPeriodSeconds: ${APPLICATION_EVENTMONITORSERVICE_POLLINGPERIODSECONDS}
  dumperService:
    pollingPeriodSeconds: ${APPLICATION_DUMPERSERVICE_POLLINGPERIODSECONDS}
  scanResultsService:
    pollingPeriodSeconds: ${APPLICATION_SCANRESULTSSERVICE_POLLINGPERIODSECONDS}
cf:
  baseUrl: ${CF_BASEURL}
  skipSslValidation: ${CF_SKIPSSLVALIDATION}
  oauth2:
    client:
      id: ${CF_OAUTH2_CLIENT_ID}
      grantType: ${CF_OAUTH2_CLIENT_GRANTTYPE}
      clientId: ${CF_OAUTH2_CLIENT_CLIENTID}
      clientSecret: ${CF_OAUTH2_CLIENT_CLIENTSECRET}
      accessTokenUri: ${CF_OAUTH2_CLIENT_ACCESSTOKENURI}
      scope: ${CF_OAUTH2_CLIENT_SCOPE}
perceptor:
  baseUrl: ${PERCEPTOR_BASEURL}
  port: ${PERCEPTOR_PORT}
broker:
  baseUrl: ${BROKER_BASEURL}
  port: ${BROKER_PORT}
  basicAuth:
    userEnvVblName: SECURITY_USER_NAME
    passEnvVblName: SECURITY_USER_PASSWORD
logging:
  level:
    root: WARN
    com:
      blackducksoftware:
        integration:
          cloudfoundry:
            perceiver: ${LOGGING_LEVEL_COM_BLACKDUCKSOFTWARE_INTEGRATION_CLOUDFOUNDRY_PERCEIVER:WARN}